# Importación de dataset

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
df_portatiles_test = pd.read_csv("data/test.csv", sep=",")
df_portatiles_test.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,181,1098,HP,Spectre x360,Ultrabook,13.3,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7500U 2.7GHz,16GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.3kg
1,708,330,Acer,Aspire 5,Notebook,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,8GB,256GB SSD,AMD Radeon RX 540,Windows 10,2.2kg
2,862,1260,Acer,Aspire ES1-572,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,500GB HDD,Intel HD Graphics 520,Linux,2.4kg
3,1064,1137,HP,EliteBook 1040,Notebook,14.0,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.43kg
4,702,1015,HP,ENVY -,Notebook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.34kg

In [3]:
df_portatiles_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                391 non-null    int64
 1   laptop_ID         391 non-null    int64
 2   Company           391 non-null    object
 3   Product           391 non-null    object
 4   TypeName          391 non-null    object
 5   Inches            391 non-null    float64
 6   ScreenResolution  391 non-null    object
 7   Cpu               391 non-null    object
 8   Ram               391 non-null    object
 9   Memory            391 non-null    object
 10  Gpu               391 non-null    object
 11  OpSys             391 non-null    object
 12  Weight            391 non-null    object
dtypes: float64(1), int64(2), object(10)
memory usage: 39.8+ KB

In [4]:
df_portatiles_test.groupby("Company")["Company"].count()

Company
Acer         28
Apple         4
Asus         50
Chuwi         1
Dell         90
Google        1
HP           85
Huawei        1
LG            2
Lenovo       89
MSI          20
Microsoft     3
Razer         1
Samsung       3
Toshiba      11
Vero          1
Xiaomi        1
Name: Company, dtype: int64

In [5]:
df_portatiles_test.groupby(["Company", "Product"])["Company"].count()

Company  Product
Acer     A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce    1
         Aspire 3                                    2
         Aspire 5                                    2
         Aspire 7                                    2
         Aspire A315-31                              1
                                                    ..
Toshiba  Tecra X40-D-10H                             1
         Tecra X40-D-10Z                             1
         Tecra Z40-C-12Z                             1
Vero     V131 (X5-Z8350/4GB/32GB/FHD/W10)            1
Xiaomi   Mi Notebook                                 1
Name: Company, Length: 269, dtype: int64

In [6]:
df_portatiles_test.groupby("TypeName")["TypeName"].count()

TypeName
2 in 1 Convertible     36
Gaming                 67
Netbook                11
Notebook              205
Ultrabook              61
Workstation            11
Name: TypeName, dtype: int64

In [7]:
df_portatiles_test.groupby("ScreenResolution")["ScreenResolution"].count()

ScreenResolution
1366x768                                          73
1440x900                                           2
1600x900                                          12
2560x1440                                          1
4K Ultra HD / Touchscreen 3840x2160                2
4K Ultra HD 3840x2160                              2
Full HD / Touchscreen 1920x1080                   15
Full HD 1920x1080                                161
IPS Panel 1366x768                                 2
IPS Panel 2560x1440                                1
IPS Panel 4K Ultra HD / Touchscreen 3840x2160      3
IPS Panel 4K Ultra HD 3840x2160                    2
IPS Panel Full HD / Touchscreen 1920x1080         16
IPS Panel Full HD 1366x768                         1
IPS Panel Full HD 1920x1080                       67
IPS Panel Full HD 2160x1440                        1
IPS Panel Full HD 2560x1440                        1
IPS Panel Quad HD+ / Touchscreen 3200x1800         2
IPS Panel Quad HD+ 2560x1440                       2
IPS Panel Quad HD+ 3200x1800                       1
IPS Panel Retina Display 2560x1600                 1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Retina Display 2880x1800                 1
IPS Panel Touchscreen 1366x768                     2
IPS Panel Touchscreen 2400x1600                    1
IPS Panel Touchscreen 2560x1440                    1
Quad HD+ / Touchscreen 3200x1800                   7
Quad HD+ 3200x1800                                 1
Touchscreen / Quad HD+ 3200x1800                   1
Touchscreen 1366x768                               1
Touchscreen 2256x1504                              3
Touchscreen 2400x1600                              1
Touchscreen 2560x1440                              3
Name: ScreenResolution, dtype: int64

In [8]:
df_portatiles_test.groupby("Cpu")["Cpu"].count()

Cpu
AMD A10-Series 9600P 2.4GHz             2
AMD A10-Series 9620P 2.5GHz             1
AMD A12-Series 9720P 2.7GHz             1
AMD A12-Series 9720P 3.6GHz             1
AMD A4-Series 7210 2.2GHz               1
                                       ..
Intel Core i7 8650U 1.9GHz              1
Intel Pentium Quad Core N3700 1.6GHz    1
Intel Pentium Quad Core N3710 1.6GHz    1
Intel Pentium Quad Core N4200 1.1GHz    2
Samsung Cortex A72&A53 2.0GHz           1
Name: Cpu, Length: 67, dtype: int64

In [9]:
df_portatiles_test.groupby("Ram")["Ram"].count()

Ram
12GB     10
16GB     75
24GB      1
2GB       6
32GB      3
4GB     101
64GB      1
6GB       9
8GB     185
Name: Ram, dtype: int64

In [10]:
df_portatiles_test.groupby("Memory")["Memory"].count()

Memory
1.0TB Hybrid                2
128GB Flash Storage         2
128GB HDD                   1
128GB SSD                  20
128GB SSD +  1TB HDD       33
128GB SSD +  2TB HDD        1
16GB Flash Storage          3
1TB HDD                    73
1TB SSD                     5
256GB Flash Storage         1
256GB SSD                 119
256GB SSD +  1TB HDD       21
256GB SSD +  256GB SSD      1
256GB SSD +  2TB HDD        6
2TB HDD                     5
32GB Flash Storage         11
32GB SSD                    1
500GB HDD                  32
508GB Hybrid                1
512GB SSD                  43
512GB SSD +  1TB HDD        4
512GB SSD +  256GB SSD      1
512GB SSD +  2TB HDD        1
64GB Flash Storage          4
Name: Memory, dtype: int64

In [11]:
df_portatiles_test.groupby("Gpu")["Gpu"].count()

Gpu
AMD FirePro W4190M       1
AMD FirePro W5130M       1
AMD Radeon 520           6
AMD Radeon 530          14
AMD Radeon 540           1
                        ..
Nvidia Quadro M1200      2
Nvidia Quadro M2200      1
Nvidia Quadro M2200M     2
Nvidia Quadro M520M      1
Nvidia Quadro M620       3
Name: Gpu, Length: 74, dtype: int64

In [12]:
df_portatiles_test.groupby("OpSys")["OpSys"].count()

OpSys
Chrome OS         7
Linux            15
Mac OS X          2
No OS            22
Windows 10      326
Windows 10 S      4
Windows 7        13
macOS             2
Name: OpSys, dtype: int64

In [13]:
df_portatiles_test.groupby("Weight")["Weight"].count()

Weight
0.91kg    1
0.97kg    1
0.98kg    1
1.05kg    3
1.08kg    1
         ..
4.3kg     2
4.42kg    3
4.5kg     1
4.6kg     1
4.7kg     1
Name: Weight, Length: 125, dtype: int64

# PROCESADO DE DATOS

| Columna          | ¿Qué hacer?                         |
|------------------|--------------------------------------|
| Company          | One-hot / Label                      |
| TypeName         | One-hot / Label                      |
| OpSys            | One-hot / Label                      |
| Gpu              | One-hot / Label                      |
| Product          | (opcional) One-hot                   |
| Ram              | Extraer número (GB)                  |
| Weight           | Extraer número (kg)                  |
| Memory           | Separar SSD/HDD y tamaños            |
| ScreenResolution | Extraer ancho/alto/IPS/Touch         |
| Cpu              | Extraer marca, modelo, GHz           |

## Borramos las columnas id, laptop_ID y Product ya que no aportan

In [14]:
df_portatiles_test = df_portatiles_test.drop(columns=["laptop_ID", "Product"])

In [15]:
df_portatiles_test.head()

,id,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,181,HP,Ultrabook,13.3,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7500U 2.7GHz,16GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.3kg
1,708,Acer,Notebook,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,8GB,256GB SSD,AMD Radeon RX 540,Windows 10,2.2kg
2,862,Acer,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,500GB HDD,Intel HD Graphics 520,Linux,2.4kg
3,1064,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.43kg
4,702,HP,Notebook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.34kg

## Transformación a valores numéricos de las columnas Ram y Weight

In [16]:
df_portatiles_test["Ram"] = df_portatiles_test["Ram"].str.replace("GB", "").astype(float)
df_portatiles_test["Weight"] = df_portatiles_test["Weight"].str.replace("kg", "").astype(float)

In [17]:
df_portatiles_test.head()

,id,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,181,HP,Ultrabook,13.3,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7500U 2.7GHz,16.0,512GB SSD,Intel HD Graphics 620,Windows 10,1.30
1,708,Acer,Notebook,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,8.0,256GB SSD,AMD Radeon RX 540,Windows 10,2.20
2,862,Acer,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4.0,500GB HDD,Intel HD Graphics 520,Linux,2.40
3,1064,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.43
4,702,HP,Notebook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,Windows 10,1.34

In [18]:
df_portatiles_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                391 non-null    int64
 1   Company           391 non-null    object
 2   TypeName          391 non-null    object
 3   Inches            391 non-null    float64
 4   ScreenResolution  391 non-null    object
 5   Cpu               391 non-null    object
 6   Ram               391 non-null    float64
 7   Memory            391 non-null    object
 8   Gpu               391 non-null    object
 9   OpSys             391 non-null    object
 10  Weight            391 non-null    float64
dtypes: float64(3), int64(1), object(7)
memory usage: 33.7+ KB

## Transformación de columnas con Label Encoder: Company, Typename y OpSys

In [20]:
# Transformación de columna Company
le_company = LabelEncoder()
df_portatiles_test["Company"] = le_company.fit_transform(df_portatiles_test["Company"])

In [21]:
# Transformación de columna Typename
le_TypeName = LabelEncoder()
df_portatiles_test["TypeName"] = le_company.fit_transform(df_portatiles_test["TypeName"])

In [22]:
# Transformación de columna OpSys
le_company = LabelEncoder()
df_portatiles_test["OpSys"] = le_company.fit_transform(df_portatiles_test["OpSys"])

In [23]:
df_portatiles_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                391 non-null    int64
 1   Company           391 non-null    int64
 2   TypeName          391 non-null    int64
 3   Inches            391 non-null    float64
 4   ScreenResolution  391 non-null    object
 5   Cpu               391 non-null    object
 6   Ram               391 non-null    float64
 7   Memory            391 non-null    object
 8   Gpu               391 non-null    object
 9   OpSys             391 non-null    int64
 10  Weight            391 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 33.7+ KB

## Extracción y transformación de columna ScreenResolution

In [24]:
# Extracción de ancho y alto
resoluciones = df_portatiles_test['ScreenResolution'].str.extract(r'(\d+)x(\d+)')

# Conversión a int
df_portatiles_test['ScreenWidth'] = resoluciones[0].astype(int)
df_portatiles_test['ScreenHeight'] = resoluciones[1].astype(int)

In [25]:
df_portatiles_test['ScreenWidth']

0      3840
1      1366
2      1366
3      1920
4      1920
       ...
386    1920
387    1920
388    1366
389    1920
390    1920
Name: ScreenWidth, Length: 391, dtype: int64

In [26]:
df_portatiles_test['ScreenHeight']

0      2160
1       768
2       768
3      1080
4      1080
       ...
386    1080
387    1080
388     768
389    1080
390    1080
Name: ScreenHeight, Length: 391, dtype: int64

In [27]:
df_portatiles_test['Touchscreen'] = df_portatiles_test['ScreenResolution'].str.contains('Touchscreen', case=False, na=False).astype(int)
df_portatiles_test['IPS'] = df_portatiles_test['ScreenResolution'].str.contains('IPS', case=False, na=False).astype(int)

In [28]:
df_portatiles_test['Touchscreen']

0      0
1      0
2      0
3      0
4      0
      ..
386    0
387    0
388    0
389    0
390    1
Name: Touchscreen, Length: 391, dtype: int64

In [29]:
df_portatiles_test['IPS']

0      1
1      0
2      0
3      0
4      1
      ..
386    1
387    1
388    0
389    0
390    1
Name: IPS, Length: 391, dtype: int64

In [30]:
# Borramos la columna ScreenResolution 
df_portatiles_test = df_portatiles_test.drop("ScreenResolution", axis=1)
df_portatiles_test.head()

,id,Company,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,ScreenWidth,ScreenHeight,Touchscreen,IPS
0,181,6,4,13.3,Intel Core i7 7500U 2.7GHz,16.0,512GB SSD,Intel HD Graphics 620,4,1.30,3840,2160,0,1
1,708,0,3,15.6,AMD A12-Series 9720P 2.7GHz,8.0,256GB SSD,AMD Radeon RX 540,4,2.20,1366,768,0,0
2,862,0,3,15.6,Intel Core i3 6006U 2.0GHz,4.0,500GB HDD,Intel HD Graphics 520,1,2.40,1366,768,0,0
3,1064,6,3,14.0,Intel Core i5 6200U 2.3GHz,8.0,256GB SSD,Intel HD Graphics 520,6,1.43,1920,1080,0,0
4,702,6,3,13.3,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,4,1.34,1920,1080,0,1

## Extracción y transformación de columna Cpu

In [31]:
marca_cpu = df_portatiles_test["Cpu"].str.extract(r'^(Intel|AMD)')
df_portatiles_test["marca_cpu"] = marca_cpu

In [32]:
le_marca_cpu = LabelEncoder()
df_portatiles_test["marca_cpu"] = le_company.fit_transform(df_portatiles_test["marca_cpu"])

In [33]:
velocidad_cpu = df_portatiles_test["Cpu"].str.extract(r'(\d+\.?\d*)GHz')

In [34]:
df_portatiles_test["velocidad_cpu"] = velocidad_cpu.astype(float)

In [36]:
df_portatiles_test = df_portatiles_test.drop("Cpu", axis=1)

In [37]:
df_portatiles_test.head()

,id,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,ScreenWidth,ScreenHeight,Touchscreen,IPS,marca_cpu,velocidad_cpu
0,181,6,4,13.3,16.0,512GB SSD,Intel HD Graphics 620,4,1.30,3840,2160,0,1,1,2.7
1,708,0,3,15.6,8.0,256GB SSD,AMD Radeon RX 540,4,2.20,1366,768,0,0,0,2.7
2,862,0,3,15.6,4.0,500GB HDD,Intel HD Graphics 520,1,2.40,1366,768,0,0,1,2.0
3,1064,6,3,14.0,8.0,256GB SSD,Intel HD Graphics 520,6,1.43,1920,1080,0,0,1,2.3
4,702,6,3,13.3,8.0,256GB SSD,Intel HD Graphics 620,4,1.34,1920,1080,0,1,1,2.5

## Extracción y transformación de columna Memory

In [38]:
# Columna para calcular el total de almacenamiento en GB
df_portatiles_test["total_almacenamiento_gb"] = (
    df_portatiles_test["Memory"]
        .str.extractall(r'(\d+)\s*(GB|TB)')
        .apply(lambda x: float(x[0]) * (1024 if x[1]=="TB" else 1), axis=1)
        .groupby(level=0).sum()
)

In [39]:
# Columnas para saber si el ordenador tiene SSD, HDD o Flash Storage
df_portatiles_test["ssd"] = df_portatiles_test['Memory'].str.contains(r'SSD', case=False).astype(int)
df_portatiles_test["hdd"] = df_portatiles_test['Memory'].str.contains(r'HDD', case=False).astype(int)
df_portatiles_test["flash"] = df_portatiles_test['Memory'].str.contains(r'Flash Storage', case=False).astype(int)

In [40]:
df_portatiles_test = df_portatiles_test.drop("Memory", axis=1)

In [41]:
df_portatiles_test

,id,Company,TypeName,Inches,Ram,Gpu,OpSys,Weight,ScreenWidth,ScreenHeight,Touchscreen,IPS,marca_cpu,velocidad_cpu,total_almacenamiento_gb,ssd,hdd,flash
0,181,6,4,13.3,16.0,Intel HD Graphics 620,4,1.30,3840,2160,0,1,1,2.7,512.0,1,0,0
1,708,0,3,15.6,8.0,AMD Radeon RX 540,4,2.20,1366,768,0,0,0,2.7,256.0,1,0,0
2,862,0,3,15.6,4.0,Intel HD Graphics 520,1,2.40,1366,768,0,0,1,2.0,500.0,0,1,0
3,1064,6,3,14.0,8.0,Intel HD Graphics 520,6,1.43,1920,1080,0,0,1,2.3,256.0,1,0,0
4,702,6,3,13.3,8.0,Intel HD Graphics 620,4,1.34,1920,1080,0,1,1,2.5,256.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,1281,9,1,15.6,8.0,Nvidia GeForce GTX 1050M,3,2.40,1920,1080,0,1,1,2.8,256.0,1,0,0
387,524,9,1,15.6,16.0,Nvidia GeForce GTX 960,4,3.31,1920,1080,0,1,1,2.6,512.0,1,0,0
388,1015,6,3,15.6,4.0,Intel HD Graphics 620,3,1.96,1366,768,0,0,1,2.5,500.0,0,1,0
389,1236,6,3,15.6,4.0,AMD Radeon R2,4,2.10,1920,1080,0,0,0,1.5,500.0,0,1,0
390,1036,9,0,13.9,8.0,Intel UHD Graphics 620,4,1.37,1920,1080,1,1,1,1.8,512.0,1,0,0

In [42]:
df_portatiles_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       391 non-null    int64
 1   Company                  391 non-null    int64
 2   TypeName                 391 non-null    int64
 3   Inches                   391 non-null    float64
 4   Ram                      391 non-null    float64
 5   Gpu                      391 non-null    object
 6   OpSys                    391 non-null    int64
 7   Weight                   391 non-null    float64
 8   ScreenWidth              391 non-null    int64
 9   ScreenHeight             391 non-null    int64
 10  Touchscreen              391 non-null    int64
 11  IPS                      391 non-null    int64
 12  marca_cpu                391 non-null    int64
 13  velocidad_cpu            391 non-null    float64
 14  total_almacenamiento_gb  391 non-null    float64
 15  ssd                      391 non-null    int64
 16  hdd                      391 non-null    int64
 17  flash                    391 non-null    int64
dtypes: float64(5), int64(12), object(1)
memory usage: 55.1+ KB

## Extracción y transformación de columna Gpu

In [43]:
# Columnas para saber si la marca de la GPU es Intel, AMD o Nvidia
df_portatiles_test["GPU_Intel"] = df_portatiles_test['Gpu'].str.contains(r'Intel', case=False).astype(int)
df_portatiles_test["GPU_AMD"] = df_portatiles_test['Gpu'].str.contains(r'AMD', case=False).astype(int)
df_portatiles_test["GPU_Nvidia"] = df_portatiles_test['Gpu'].str.contains(r'Nvidia', case=False).astype(int)

In [44]:
df_portatiles_test = df_portatiles_test.drop("Gpu", axis=1)

In [45]:
df_portatiles_test

,id,Company,TypeName,Inches,Ram,OpSys,Weight,ScreenWidth,ScreenHeight,Touchscreen,IPS,marca_cpu,velocidad_cpu,total_almacenamiento_gb,ssd,hdd,flash,GPU_Intel,GPU_AMD,GPU_Nvidia
0,181,6,4,13.3,16.0,4,1.30,3840,2160,0,1,1,2.7,512.0,1,0,0,1,0,0
1,708,0,3,15.6,8.0,4,2.20,1366,768,0,0,0,2.7,256.0,1,0,0,0,1,0
2,862,0,3,15.6,4.0,1,2.40,1366,768,0,0,1,2.0,500.0,0,1,0,1,0,0
3,1064,6,3,14.0,8.0,6,1.43,1920,1080,0,0,1,2.3,256.0,1,0,0,1,0,0
4,702,6,3,13.3,8.0,4,1.34,1920,1080,0,1,1,2.5,256.0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,1281,9,1,15.6,8.0,3,2.40,1920,1080,0,1,1,2.8,256.0,1,0,0,0,0,1
387,524,9,1,15.6,16.0,4,3.31,1920,1080,0,1,1,2.6,512.0,1,0,0,0,0,1
388,1015,6,3,15.6,4.0,3,1.96,1366,768,0,0,1,2.5,500.0,0,1,0,1,0,0
389,1236,6,3,15.6,4.0,4,2.10,1920,1080,0,0,0,1.5,500.0,0,1,0,0,1,0
390,1036,9,0,13.9,8.0,4,1.37,1920,1080,1,1,1,1.8,512.0,1,0,0,1,0,0

In [46]:
df_portatiles_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       391 non-null    int64
 1   Company                  391 non-null    int64
 2   TypeName                 391 non-null    int64
 3   Inches                   391 non-null    float64
 4   Ram                      391 non-null    float64
 5   OpSys                    391 non-null    int64
 6   Weight                   391 non-null    float64
 7   ScreenWidth              391 non-null    int64
 8   ScreenHeight             391 non-null    int64
 9   Touchscreen              391 non-null    int64
 10  IPS                      391 non-null    int64
 11  marca_cpu                391 non-null    int64
 12  velocidad_cpu            391 non-null    float64
 13  total_almacenamiento_gb  391 non-null    float64
 14  ssd                      391 non-null    int64
 15  hdd                      391 non-null    int64
 16  flash                    391 non-null    int64
 17  GPU_Intel                391 non-null    int64
 18  GPU_AMD                  391 non-null    int64
 19  GPU_Nvidia               391 non-null    int64
dtypes: float64(5), int64(15)
memory usage: 61.2 KB

## Exportamos el dataframe a csv para modelar

In [48]:
df_portatiles_test.to_csv("data/test_kaggle_procesado.csv", index=False)