# Importación de dataset

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
df_portatiles_train = pd.read_csv("data/train.csv", sep=",")
df_portatiles_train.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,268,1002,Dell,Inspiron 5567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R7 M445,Windows 10,2.36kg,749.00
1,347,867,Asus,X541NA (N4200/4GB/1TB/W10),Notebook,15.6,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Intel HD Graphics 505,Windows 10,2kg,449.00
2,353,966,Toshiba,Portege Z30-C-1CW,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.2kg,1460.00
3,578,767,Dell,Alienware 17,Gaming,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.42kg,2868.99
4,42,1241,Dell,Latitude E7270,Ultrabook,12.5,Full HD / Touchscreen 1920x1080,Intel Core i5 6300U 2.4GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.26kg,1713.37

In [3]:
df_portatiles_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   laptop_ID         912 non-null    int64
 2   Company           912 non-null    object
 3   Product           912 non-null    object
 4   TypeName          912 non-null    object
 5   Inches            912 non-null    float64
 6   ScreenResolution  912 non-null    object
 7   Cpu               912 non-null    object
 8   Ram               912 non-null    object
 9   Memory            912 non-null    object
 10  Gpu               912 non-null    object
 11  OpSys             912 non-null    object
 12  Weight            912 non-null    object
 13  Price_euros       912 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 99.9+ KB

In [4]:
df_portatiles_train.groupby("Company")["Company"].count()

Company
Acer          75
Apple         17
Asus         108
Chuwi          2
Dell         207
Fujitsu        3
Google         2
HP           189
Huawei         1
LG             1
Lenovo       208
MSI           34
Mediacom       7
Microsoft      3
Razer          6
Samsung        6
Toshiba       37
Vero           3
Xiaomi         3
Name: Company, dtype: int64

In [5]:
df_portatiles_train.groupby(["Company", "Product"])["Company"].count()

Company  Product
Acer     Aspire 1                          1
         Aspire 3                         10
         Aspire 5                          5
         Aspire 7                          2
         Aspire A315-31                    1
                                          ..
Toshiba  Tecra Z50-D-10E                   1
Vero     K146 (N3350/4GB/32GB/W10)         1
         K147 (N3350/4GB/32GB/FHD/W10)     1
         V142 (X5-Z8350/2GB/32GB/W10)      1
Xiaomi   Mi Notebook                       3
Name: Company, Length: 475, dtype: int64

In [6]:
df_portatiles_train.groupby("TypeName")["TypeName"].count()

TypeName
2 in 1 Convertible     85
Gaming                138
Netbook                14
Notebook              522
Ultrabook             135
Workstation            18
Name: TypeName, dtype: int64

In [7]:
df_portatiles_train.groupby("ScreenResolution")["ScreenResolution"].count()

ScreenResolution
1366x768                                         208
1440x900                                           2
1600x900                                          11
1920x1080                                          3
2560x1440                                          2
4K Ultra HD / Touchscreen 3840x2160                8
4K Ultra HD 3840x2160                              5
Full HD / Touchscreen 1920x1080                   32
Full HD 1920x1080                                346
IPS Panel 1366x768                                 5
IPS Panel 2560x1440                                3
IPS Panel 4K Ultra HD / Touchscreen 3840x2160      8
IPS Panel 4K Ultra HD 3840x2160                   10
IPS Panel Full HD / Touchscreen 1920x1080         37
IPS Panel Full HD 1920x1080                      163
IPS Panel Full HD 1920x1200                        1
IPS Panel Full HD 2160x1440                        1
IPS Panel Quad HD+ / Touchscreen 3200x1800         4
IPS Panel Quad HD+ 2560x1440                       1
IPS Panel Quad HD+ 3200x1800                       1
IPS Panel Retina Display 2304x1440                 6
IPS Panel Retina Display 2560x1600                 5
IPS Panel Retina Display 2880x1800                 3
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Touchscreen 1366x768                     1
IPS Panel Touchscreen 1920x1200                    4
IPS Panel Touchscreen 2560x1440                    4
Quad HD+ / Touchscreen 3200x1800                   8
Quad HD+ 3200x1800                                 2
Touchscreen / 4K Ultra HD 3840x2160                1
Touchscreen / Full HD 1920x1080                    1
Touchscreen 1366x768                              15
Touchscreen 2256x1504                              3
Touchscreen 2400x1600                              2
Touchscreen 2560x1440                              4
Name: ScreenResolution, dtype: int64

In [8]:
df_portatiles_train.groupby("Cpu")["Cpu"].count()

Cpu
AMD A10-Series 9620P 2.5GHz              1
AMD A10-Series A10-9620P 2.5GHz          2
AMD A12-Series 9700P 2.5GHz              1
AMD A12-Series 9720P 2.7GHz              1
AMD A12-Series 9720P 3.6GHz              4
                                        ..
Intel Pentium Quad Core N3710 1.6GHz    10
Intel Pentium Quad Core N4200 1.1GHz    12
Intel Xeon E3-1505M V6 3GHz              2
Intel Xeon E3-1535M v5 2.9GHz            1
Intel Xeon E3-1535M v6 3.1GHz            1
Name: Cpu, Length: 104, dtype: int64

In [9]:
df_portatiles_train.groupby("Ram")["Ram"].count()

Ram
12GB     15
16GB    125
24GB      2
2GB      16
32GB     14
4GB     274
6GB      32
8GB     434
Name: Ram, dtype: int64

In [10]:
df_portatiles_train.groupby("Memory")["Memory"].count()

Memory
1.0TB HDD                          1
1.0TB Hybrid                       7
128GB Flash Storage                2
128GB SSD                         56
128GB SSD +  1TB HDD              61
128GB SSD +  2TB HDD               1
16GB Flash Storage                 4
16GB SSD                           3
180GB SSD                          5
1TB HDD                          150
1TB HDD +  1TB HDD                 1
1TB SSD                            9
1TB SSD +  1TB HDD                 2
240GB SSD                          1
256GB Flash Storage                7
256GB SSD                        293
256GB SSD +  1.0TB Hybrid          1
256GB SSD +  1TB HDD              52
256GB SSD +  256GB SSD             1
256GB SSD +  2TB HDD               4
256GB SSD +  500GB HDD             2
2TB HDD                           11
32GB Flash Storage                27
32GB HDD                           1
32GB SSD                           5
500GB HDD                        100
512GB Flash Storage                2
512GB SSD                         75
512GB SSD +  1.0TB Hybrid          1
512GB SSD +  1TB HDD              10
512GB SSD +  2TB HDD               2
512GB SSD +  512GB SSD             1
64GB Flash Storage                11
64GB Flash Storage +  1TB HDD      1
64GB SSD                           1
8GB SSD                            1
Name: Memory, dtype: int64

In [11]:
df_portatiles_train.groupby("Gpu")["Gpu"].count()

Gpu
AMD FirePro W4190M       2
AMD FirePro W6150M       1
AMD R17M-M1-70           1
AMD R4 Graphics          1
AMD Radeon 520          11
                        ..
Nvidia Quadro M3000M     1
Nvidia Quadro M500M      1
Nvidia Quadro M520M      1
Nvidia Quadro M620       2
Nvidia Quadro M620M      1
Name: Gpu, Length: 91, dtype: int64

In [12]:
df_portatiles_train.groupby("OpSys")["OpSys"].count()

OpSys
Android           2
Chrome OS        20
Linux            47
Mac OS X          6
No OS            44
Windows 10      746
Windows 10 S      4
Windows 7        32
macOS            11
Name: OpSys, dtype: int64

In [13]:
df_portatiles_train.groupby("Weight")["Weight"].count()

Weight
0.69kg     4
0.81kg     2
0.920kg    4
0.92kg     2
0.97kg     1
          ..
4.3kg      2
4.42kg     8
4.4kg      1
4.6kg      3
4kg        1
Name: Weight, Length: 158, dtype: int64

# PROCESADO DE DATOS

| Columna          | ¿Qué hacer?                         |
|------------------|--------------------------------------|
| Company          | One-hot / Label                      |
| TypeName         | One-hot / Label                      |
| OpSys            | One-hot / Label                      |
| Gpu              | One-hot / Label                      |
| Product          | (opcional) One-hot                   |
| Ram              | Extraer número (GB)                  |
| Weight           | Extraer número (kg)                  |
| Memory           | Separar SSD/HDD y tamaños            |
| ScreenResolution | Extraer ancho/alto/IPS/Touch         |
| Cpu              | Extraer marca, modelo, GHz           |

## Borramos las columnas id, laptop_ID y Product ya que no aportan

In [14]:
df_portatiles_train = df_portatiles_train.drop(columns=["laptop_ID", "Product"])

In [15]:
df_portatiles_train.head()

,id,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,268,Dell,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R7 M445,Windows 10,2.36kg,749.00
1,347,Asus,Notebook,15.6,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Intel HD Graphics 505,Windows 10,2kg,449.00
2,353,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.2kg,1460.00
3,578,Dell,Gaming,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.42kg,2868.99
4,42,Dell,Ultrabook,12.5,Full HD / Touchscreen 1920x1080,Intel Core i5 6300U 2.4GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.26kg,1713.37

## Transformación a valores numéricos de las columnas Ram y Weight

In [16]:
df_portatiles_train["Ram"] = df_portatiles_train["Ram"].str.replace("GB", "").astype(float)
df_portatiles_train["Weight"] = df_portatiles_train["Weight"].str.replace("kg", "").astype(float)

In [17]:
df_portatiles_train.head()

,id,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,268,Dell,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8.0,1TB HDD,AMD Radeon R7 M445,Windows 10,2.36,749.00
1,347,Asus,Notebook,15.6,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4.0,1TB HDD,Intel HD Graphics 505,Windows 10,2.00,449.00
2,353,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.20,1460.00
3,578,Dell,Gaming,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,16.0,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.42,2868.99
4,42,Dell,Ultrabook,12.5,Full HD / Touchscreen 1920x1080,Intel Core i5 6300U 2.4GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.26,1713.37

In [18]:
df_portatiles_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   Company           912 non-null    object
 2   TypeName          912 non-null    object
 3   Inches            912 non-null    float64
 4   ScreenResolution  912 non-null    object
 5   Cpu               912 non-null    object
 6   Ram               912 non-null    float64
 7   Memory            912 non-null    object
 8   Gpu               912 non-null    object
 9   OpSys             912 non-null    object
 10  Weight            912 non-null    float64
 11  Price_euros       912 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 85.6+ KB

## Transformación de columnas con Label Encoder: Company, Typename y OpSys

In [19]:
# Transformación de columna Company
le_company = LabelEncoder()
df_portatiles_train["Company"] = le_company.fit_transform(df_portatiles_train["Company"])

In [20]:
# Transformación de columna Typename
le_TypeName = LabelEncoder()
df_portatiles_train["TypeName"] = le_company.fit_transform(df_portatiles_train["TypeName"])

In [21]:
# Transformación de columna OpSys
le_company = LabelEncoder()
df_portatiles_train["OpSys"] = le_company.fit_transform(df_portatiles_train["OpSys"])

In [22]:
df_portatiles_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   Company           912 non-null    int64
 2   TypeName          912 non-null    int64
 3   Inches            912 non-null    float64
 4   ScreenResolution  912 non-null    object
 5   Cpu               912 non-null    object
 6   Ram               912 non-null    float64
 7   Memory            912 non-null    object
 8   Gpu               912 non-null    object
 9   OpSys             912 non-null    int64
 10  Weight            912 non-null    float64
 11  Price_euros       912 non-null    float64
dtypes: float64(4), int64(4), object(4)
memory usage: 85.6+ KB

## Extracción y transformación de columna ScreenResolution

In [23]:
# Extracción de ancho y alto
resoluciones = df_portatiles_train['ScreenResolution'].str.extract(r'(\d+)x(\d+)')

# Conversión a int
df_portatiles_train['ScreenWidth'] = resoluciones[0].astype(int)
df_portatiles_train['ScreenHeight'] = resoluciones[1].astype(int)

In [24]:
df_portatiles_train['ScreenWidth']

0      1366
1      1366
2      1920
3      3840
4      1920
       ...
907    1366
908    1920
909    1366
910    1920
911    1366
Name: ScreenWidth, Length: 912, dtype: int64

In [25]:
df_portatiles_train['ScreenHeight']

0       768
1       768
2      1080
3      2160
4      1080
       ...
907     768
908    1080
909     768
910    1080
911     768
Name: ScreenHeight, Length: 912, dtype: int64

In [26]:
df_portatiles_train['Touchscreen'] = df_portatiles_train['ScreenResolution'].str.contains('Touchscreen', case=False, na=False).astype(int)
df_portatiles_train['IPS'] = df_portatiles_train['ScreenResolution'].str.contains('IPS', case=False, na=False).astype(int)

In [27]:
df_portatiles_train['Touchscreen']

0      0
1      0
2      0
3      0
4      1
      ..
907    1
908    0
909    0
910    0
911    0
Name: Touchscreen, Length: 912, dtype: int64

In [28]:
df_portatiles_train['IPS']

0      0
1      0
2      0
3      1
4      0
      ..
907    1
908    0
909    0
910    0
911    0
Name: IPS, Length: 912, dtype: int64

In [29]:
# Borramos la columna ScreenResolution 
df_portatiles_train = df_portatiles_train.drop("ScreenResolution", axis=1)
df_portatiles_train.head()

,id,Company,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,ScreenWidth,ScreenHeight,Touchscreen,IPS
0,268,4,3,15.6,Intel Core i7 7500U 2.7GHz,8.0,1TB HDD,AMD Radeon R7 M445,5,2.36,749.00,1366,768,0,0
1,347,2,3,15.6,Intel Pentium Quad Core N4200 1.1GHz,4.0,1TB HDD,Intel HD Graphics 505,5,2.00,449.00,1366,768,0,0
2,353,16,3,13.3,Intel Core i5 6200U 2.3GHz,8.0,256GB SSD,Intel HD Graphics 520,7,1.20,1460.00,1920,1080,0,0
3,578,4,1,15.6,Intel Core i7 7700HQ 2.8GHz,16.0,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,5,4.42,2868.99,3840,2160,0,1
4,42,4,4,12.5,Intel Core i5 6300U 2.4GHz,8.0,256GB SSD,Intel HD Graphics 520,7,1.26,1713.37,1920,1080,1,0

## Extracción y transformación de columna Cpu

In [30]:
marca_cpu = df_portatiles_train["Cpu"].str.extract(r'^(Intel|AMD)')
df_portatiles_train["marca_cpu"] = marca_cpu

In [31]:
le_marca_cpu = LabelEncoder()
df_portatiles_train["marca_cpu"] = le_company.fit_transform(df_portatiles_train["marca_cpu"])

In [32]:
velocidad_cpu = df_portatiles_train["Cpu"].str.extract(r'(\d+\.?\d*)GHz')

In [33]:
df_portatiles_train["velocidad_cpu"] = velocidad_cpu.astype(float)

In [34]:
df_portatiles_train = df_portatiles_train.drop("Cpu", axis=1)

In [35]:
df_portatiles_train.head()

,id,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,Price_euros,ScreenWidth,ScreenHeight,Touchscreen,IPS,marca_cpu,velocidad_cpu
0,268,4,3,15.6,8.0,1TB HDD,AMD Radeon R7 M445,5,2.36,749.00,1366,768,0,0,1,2.7
1,347,2,3,15.6,4.0,1TB HDD,Intel HD Graphics 505,5,2.00,449.00,1366,768,0,0,1,1.1
2,353,16,3,13.3,8.0,256GB SSD,Intel HD Graphics 520,7,1.20,1460.00,1920,1080,0,0,1,2.3
3,578,4,1,15.6,16.0,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,5,4.42,2868.99,3840,2160,0,1,1,2.8
4,42,4,4,12.5,8.0,256GB SSD,Intel HD Graphics 520,7,1.26,1713.37,1920,1080,1,0,1,2.4

## Extracción y transformación de columna Memory

In [36]:
# Columna para calcular el total de almacenamiento en GB
df_portatiles_train["total_almacenamiento_gb"] = (
    df_portatiles_train["Memory"]
        .str.extractall(r'(\d+)\s*(GB|TB)')
        .apply(lambda x: float(x[0]) * (1024 if x[1]=="TB" else 1), axis=1)
        .groupby(level=0).sum()
)

In [37]:
# Columnas para saber si el ordenador tiene SSD, HDD o Flash Storage
df_portatiles_train["ssd"] = df_portatiles_train['Memory'].str.contains(r'SSD', case=False).astype(int)
df_portatiles_train["hdd"] = df_portatiles_train['Memory'].str.contains(r'HDD', case=False).astype(int)
df_portatiles_train["flash"] = df_portatiles_train['Memory'].str.contains(r'Flash Storage', case=False).astype(int)

In [38]:
df_portatiles_train = df_portatiles_train.drop("Memory", axis=1)

In [39]:
df_portatiles_train

,id,Company,TypeName,Inches,Ram,Gpu,OpSys,Weight,Price_euros,ScreenWidth,ScreenHeight,Touchscreen,IPS,marca_cpu,velocidad_cpu,total_almacenamiento_gb,ssd,hdd,flash
0,268,4,3,15.6,8.0,AMD Radeon R7 M445,5,2.36,749.00,1366,768,0,0,1,2.7,1024.0,0,1,0
1,347,2,3,15.6,4.0,Intel HD Graphics 505,5,2.00,449.00,1366,768,0,0,1,1.1,1024.0,0,1,0
2,353,16,3,13.3,8.0,Intel HD Graphics 520,7,1.20,1460.00,1920,1080,0,0,1,2.3,256.0,1,0,0
3,578,4,1,15.6,16.0,Nvidia GeForce GTX 1070,5,4.42,2868.99,3840,2160,0,1,1,2.8,1280.0,1,1,0
4,42,4,4,12.5,8.0,Intel HD Graphics 520,7,1.26,1713.37,1920,1080,1,0,1,2.4,256.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,89,0,0,11.6,4.0,Intel HD Graphics 400,1,1.25,389.00,1366,768,1,1,1,1.6,32.0,0,0,1
908,716,16,3,13.3,4.0,Intel HD Graphics 520,5,1.20,1195.00,1920,1080,0,0,1,2.3,128.0,1,0,0
909,517,0,3,15.6,8.0,AMD Radeon R5,5,2.40,449.00,1366,768,0,0,0,2.2,1024.0,0,1,0
910,891,4,4,14.0,8.0,Intel HD Graphics 620,5,1.36,1775.00,1920,1080,0,0,1,2.8,256.0,1,0,0
911,1179,4,3,15.6,8.0,AMD Radeon R5 M430,2,2.30,805.99,1366,768,0,0,1,2.7,1024.0,0,1,0

In [40]:
df_portatiles_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       912 non-null    int64
 1   Company                  912 non-null    int64
 2   TypeName                 912 non-null    int64
 3   Inches                   912 non-null    float64
 4   Ram                      912 non-null    float64
 5   Gpu                      912 non-null    object
 6   OpSys                    912 non-null    int64
 7   Weight                   912 non-null    float64
 8   Price_euros              912 non-null    float64
 9   ScreenWidth              912 non-null    int64
 10  ScreenHeight             912 non-null    int64
 11  Touchscreen              912 non-null    int64
 12  IPS                      912 non-null    int64
 13  marca_cpu                912 non-null    int64
 14  velocidad_cpu            912 non-null    float64
 15  total_almacenamiento_gb  912 non-null    float64
 16  ssd                      912 non-null    int64
 17  hdd                      912 non-null    int64
 18  flash                    912 non-null    int64
dtypes: float64(6), int64(12), object(1)
memory usage: 135.5+ KB

## Extracción y transformación de columna Gpu

In [41]:
# Columnas para saber si la marca de la GPU es Intel, AMD o Nvidia
df_portatiles_train["GPU_Intel"] = df_portatiles_train['Gpu'].str.contains(r'Intel', case=False).astype(int)
df_portatiles_train["GPU_AMD"] = df_portatiles_train['Gpu'].str.contains(r'AMD', case=False).astype(int)
df_portatiles_train["GPU_Nvidia"] = df_portatiles_train['Gpu'].str.contains(r'Nvidia', case=False).astype(int)

In [42]:
df_portatiles_train = df_portatiles_train.drop("Gpu", axis=1)

In [43]:
df_portatiles_train

,id,Company,TypeName,Inches,Ram,OpSys,Weight,Price_euros,ScreenWidth,ScreenHeight,...,IPS,marca_cpu,velocidad_cpu,total_almacenamiento_gb,ssd,hdd,flash,GPU_Intel,GPU_AMD,GPU_Nvidia
0,268,4,3,15.6,8.0,5,2.36,749.00,1366,768,...,0,1,2.7,1024.0,0,1,0,0,1,0
1,347,2,3,15.6,4.0,5,2.00,449.00,1366,768,...,0,1,1.1,1024.0,0,1,0,1,0,0
2,353,16,3,13.3,8.0,7,1.20,1460.00,1920,1080,...,0,1,2.3,256.0,1,0,0,1,0,0
3,578,4,1,15.6,16.0,5,4.42,2868.99,3840,2160,...,1,1,2.8,1280.0,1,1,0,0,0,1
4,42,4,4,12.5,8.0,7,1.26,1713.37,1920,1080,...,0,1,2.4,256.0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,89,0,0,11.6,4.0,1,1.25,389.00,1366,768,...,1,1,1.6,32.0,0,0,1,1,0,0
908,716,16,3,13.3,4.0,5,1.20,1195.00,1920,1080,...,0,1,2.3,128.0,1,0,0,1,0,0
909,517,0,3,15.6,8.0,5,2.40,449.00,1366,768,...,0,0,2.2,1024.0,0,1,0,0,1,0
910,891,4,4,14.0,8.0,5,1.36,1775.00,1920,1080,...,0,1,2.8,256.0,1,0,0,1,0,0
911,1179,4,3,15.6,8.0,2,2.30,805.99,1366,768,...,0,1,2.7,1024.0,0,1,0,0,1,0

In [44]:
df_portatiles_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       912 non-null    int64
 1   Company                  912 non-null    int64
 2   TypeName                 912 non-null    int64
 3   Inches                   912 non-null    float64
 4   Ram                      912 non-null    float64
 5   OpSys                    912 non-null    int64
 6   Weight                   912 non-null    float64
 7   Price_euros              912 non-null    float64
 8   ScreenWidth              912 non-null    int64
 9   ScreenHeight             912 non-null    int64
 10  Touchscreen              912 non-null    int64
 11  IPS                      912 non-null    int64
 12  marca_cpu                912 non-null    int64
 13  velocidad_cpu            912 non-null    float64
 14  total_almacenamiento_gb  912 non-null    float64
 15  ssd                      912 non-null    int64
 16  hdd                      912 non-null    int64
 17  flash                    912 non-null    int64
 18  GPU_Intel                912 non-null    int64
 19  GPU_AMD                  912 non-null    int64
 20  GPU_Nvidia               912 non-null    int64
dtypes: float64(6), int64(15)
memory usage: 149.8 KB

## Pasamos la columna target Price_euros al final

In [45]:
df_portatiles_train["Precio_euros"] = df_portatiles_train["Price_euros"]

In [46]:
df_portatiles_train = df_portatiles_train.drop("Price_euros", axis=1)

In [47]:
df_portatiles_train.rename(columns={"Precio_euros": "Price_euros"}, inplace=True)

In [48]:
df_portatiles_train

,id,Company,TypeName,Inches,Ram,OpSys,Weight,ScreenWidth,ScreenHeight,Touchscreen,...,marca_cpu,velocidad_cpu,total_almacenamiento_gb,ssd,hdd,flash,GPU_Intel,GPU_AMD,GPU_Nvidia,Price_euros
0,268,4,3,15.6,8.0,5,2.36,1366,768,0,...,1,2.7,1024.0,0,1,0,0,1,0,749.00
1,347,2,3,15.6,4.0,5,2.00,1366,768,0,...,1,1.1,1024.0,0,1,0,1,0,0,449.00
2,353,16,3,13.3,8.0,7,1.20,1920,1080,0,...,1,2.3,256.0,1,0,0,1,0,0,1460.00
3,578,4,1,15.6,16.0,5,4.42,3840,2160,0,...,1,2.8,1280.0,1,1,0,0,0,1,2868.99
4,42,4,4,12.5,8.0,7,1.26,1920,1080,1,...,1,2.4,256.0,1,0,0,1,0,0,1713.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,89,0,0,11.6,4.0,1,1.25,1366,768,1,...,1,1.6,32.0,0,0,1,1,0,0,389.00
908,716,16,3,13.3,4.0,5,1.20,1920,1080,0,...,1,2.3,128.0,1,0,0,1,0,0,1195.00
909,517,0,3,15.6,8.0,5,2.40,1366,768,0,...,0,2.2,1024.0,0,1,0,0,1,0,449.00
910,891,4,4,14.0,8.0,5,1.36,1920,1080,0,...,1,2.8,256.0,1,0,0,1,0,0,1775.00
911,1179,4,3,15.6,8.0,2,2.30,1366,768,0,...,1,2.7,1024.0,0,1,0,0,1,0,805.99

In [49]:
df_portatiles_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       912 non-null    int64
 1   Company                  912 non-null    int64
 2   TypeName                 912 non-null    int64
 3   Inches                   912 non-null    float64
 4   Ram                      912 non-null    float64
 5   OpSys                    912 non-null    int64
 6   Weight                   912 non-null    float64
 7   ScreenWidth              912 non-null    int64
 8   ScreenHeight             912 non-null    int64
 9   Touchscreen              912 non-null    int64
 10  IPS                      912 non-null    int64
 11  marca_cpu                912 non-null    int64
 12  velocidad_cpu            912 non-null    float64
 13  total_almacenamiento_gb  912 non-null    float64
 14  ssd                      912 non-null    int64
 15  hdd                      912 non-null    int64
 16  flash                    912 non-null    int64
 17  GPU_Intel                912 non-null    int64
 18  GPU_AMD                  912 non-null    int64
 19  GPU_Nvidia               912 non-null    int64
 20  Price_euros              912 non-null    float64
dtypes: float64(6), int64(15)
memory usage: 149.8 KB

## Exportamos el dataframe a csv para modelar

In [50]:
df_portatiles_train.to_csv("data/train_kaggle_procesado.csv", index=False)