### Importa los datos
Dataset con diferentes fármacos, sus efectos y ratings de los clientes.

Importa el dataset *drugLibTrain_raw.tsv*

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import OneHotEncoder

In [14]:
df = pd.read_csv("data/drugLibTrain_raw.tsv", sep="\t", index_col=0)
df.head()

,urlDrugName,rating,effectiveness,sideEffects,condition,benefitsReview,sideEffectsReview,commentsReview
2202,enalapril,4,Highly Effective,Mild Side Effects,management of congestive heart failure,slowed the progression of left ventricular dys...,"cough, hypotension , proteinuria, impotence , ...","monitor blood pressure , weight and asses for ..."
3117,ortho-tri-cyclen,1,Highly Effective,Severe Side Effects,birth prevention,Although this type of birth control has more c...,"Heavy Cycle, Cramps, Hot Flashes, Fatigue, Lon...","I Hate This Birth Control, I Would Not Suggest..."
1146,ponstel,10,Highly Effective,No Side Effects,menstrual cramps,I was used to having cramps so badly that they...,Heavier bleeding and clotting than normal.,I took 2 pills at the onset of my menstrual cr...
3947,prilosec,3,Marginally Effective,Mild Side Effects,acid reflux,The acid reflux went away for a few months aft...,"Constipation, dry mouth and some mild dizzines...",I was given Prilosec prescription at a dose of...
1951,lyrica,2,Marginally Effective,Severe Side Effects,fibromyalgia,I think that the Lyrica was starting to help w...,I felt extremely drugged and dopey. Could not...,See above

### Descriptive Analysis

Quedate únicamente con las columnas que podamos manejar: Columnas numéricas y columnas categóricas con pocas categorías (menos de 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3107 entries, 2202 to 2748
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   urlDrugName        3107 non-null   object
 1   rating             3107 non-null   int64
 2   effectiveness      3107 non-null   object
 3   sideEffects        3107 non-null   object
 4   condition          3106 non-null   object
 5   benefitsReview     3089 non-null   object
 6   sideEffectsReview  3032 non-null   object
 7   commentsReview     3095 non-null   object
dtypes: int64(1), object(7)
memory usage: 218.5+ KB

In [9]:
df = df[["rating","effectiveness", "sideEffects"]]
df

      rating           effectiveness                    sideEffects
2202       4        Highly Effective              Mild Side Effects
3117       1        Highly Effective            Severe Side Effects
1146      10        Highly Effective                No Side Effects
3947       3    Marginally Effective              Mild Side Effects
1951       2    Marginally Effective            Severe Side Effects
...      ...                     ...                            ...
1039      10        Highly Effective              Mild Side Effects
3281       1             Ineffective  Extremely Severe Side Effects
1664       2    Marginally Effective          Moderate Side Effects
2621       8  Considerably Effective              Mild Side Effects
2748       4    Moderately Effective          Moderate Side Effects

[3107 rows x 3 columns]

In [8]:
df.describe(include="all")

,urlDrugName,rating,effectiveness,sideEffects,condition,benefitsReview,sideEffectsReview,commentsReview
count,3107,3107.000000,3107,3107,3106,3089,3032,3095
unique,502,NaN,5,5,1426,3031,2813,3046
top,lexapro,NaN,Highly Effective,Mild Side Effects,depression,none,none,none
freq,63,NaN,1330,1019,236,20,112,6
mean,NaN,7.006115,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2.937582,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN

#### Transforma las columnas categóricas

Transforma las columnas categoricas a numericas mediante dummies

In [12]:
df = pd.get_dummies(df[["effectiveness", "sideEffects"]])
df

,effectiveness_Considerably Effective,effectiveness_Highly Effective,effectiveness_Ineffective,effectiveness_Marginally Effective,effectiveness_Moderately Effective,sideEffects_Extremely Severe Side Effects,sideEffects_Mild Side Effects,sideEffects_Moderate Side Effects,sideEffects_No Side Effects,sideEffects_Severe Side Effects
2202,False,True,False,False,False,False,True,False,False,False
3117,False,True,False,False,False,False,False,False,False,True
1146,False,True,False,False,False,False,False,False,True,False
3947,False,False,False,True,False,False,True,False,False,False
1951,False,False,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
1039,False,True,False,False,False,False,True,False,False,False
3281,False,False,True,False,False,True,False,False,False,False
1664,False,False,False,True,False,False,False,True,False,False
2621,True,False,False,False,False,False,True,False,False,False
2748,False,False,False,False,True,False,False,True,False,False

In [13]:
df["rating"] = df["rating"]

KeyError: 'rating'

#### Evalua cual es la mejor K

Utiliza silhouette_score para evaluar cual es la mejor K.

#### Genera el K Means

Comprueba los resultados y muestra en un pie plot la distribución de los distintos clusters.