# Webscrapping con Beautiful Soup

El **web scraping** es el proceso de extracción de datos de sitios web de manera automatizada. Aprenderás los conceptos fundamentales y las herramientas necesarias para recolectar datos valiosos de la web, lo que te permitirá alimentar tus análisis y proyectos de Data Science con información fresca y relevante.

## ¿Qué es?

En términos sencillos, web scraping es como recolectar datos de una página web. Imagina que la web es una mina de información y que eres un minero recogiendo las gemas que necesitas para tu proyecto. En lugar de copiar y pegar manualmente, utilizamos código para automatizar el proceso.

### ¿Por qué es importante el Web Scraping?

* **Acceso a datos no estructurados**: La mayoría de los datos en línea no están disponibles en formatos estructurados y listos para ser analizados. El web scraping te permite convertir datos no estructurados en un formato que puedas utilizar.

* **Actualización de datos**: Muchas fuentes web se actualizan constantemente. El web scraping te permite mantener tus conjuntos de datos actualizados sin tener que hacerlo manualmente.

* **Amplia gama de aplicaciones**: Desde la recopilación de datos de redes sociales hasta la obtención de precios de productos, el web scraping se utiliza en una amplia gama de aplicaciones de Data Science.

## Proceso de Web Scraping

El web scraping generalmente sigue estos pasos:

* **Hacer una solicitud HTTP**: obtenemos el contenido HTML de una página web.

* **Análisis del HTML**: analizamos la estructura del HTML y encontrar los elementos que contienen los datos que necesitamos.

* **Extracción de datos**: Una vez que hemos identificado los elementos, extraemos los datos relevantes.

* **Almacenamiento de datos**: Podemos guardar los datos en un formato estructurado, como un archivo CSV o una base de datos.

* **Limpieza y procesamiento**: A menudo, los datos extraídos necesitan ser limpiados y preprocesados antes de su análisis.

Es importante recordar que el web scraping puede tener implicaciones legales y éticas. Algunos sitios web prohíben la extracción de sus datos, y otros pueden limitar la velocidad a la que puedes hacer solicitudes para evitar la sobrecarga de sus servidores. Siempre debes respetar los términos de servicio de los sitios web y ser consciente de las leyes de privacidad y propiedad intelectual.

## Intro HTML

HTML (HyperText Markup Language) es el lenguaje de marcado utilizado para crear páginas web. Comprender los conceptos básicos de HTML es esencial para realizar web scraping, ya que te permite navegar y extraer datos de manera efectiva de sitios web.

HTML utiliza etiquetas para estructurar el contenido de una página web. Aquí tienes una breve introducción a los conceptos básicos de HTML:

1. **Etiquetas:** Las etiquetas son elementos fundamentales en HTML. Comienzan con `<` y terminan con `>`. Por ejemplo, `<p>` se utiliza para definir un párrafo, `<h1>` para encabezados de nivel 1, y `<a>` para enlaces.

2. **Elementos:** Un elemento HTML se compone de una etiqueta de apertura, contenido y una etiqueta de cierre. Por ejemplo, `<p>Este es un párrafo.</p>`. El contenido es lo que se muestra en la página.

3. **Atributos:** Las etiquetas pueden contener atributos que proporcionan información adicional sobre el elemento. Por ejemplo, en `<a href="https://www.ejemplo.com">Enlace</a>`, "href" es un atributo que define la URL a la que el enlace apunta.

4. **Anidamiento:** Los elementos HTML pueden anidarse dentro de otros elementos. Por ejemplo, un párrafo `<p>` puede contener un enlace `<a>`. Es importante entender la jerarquía de anidamiento para navegar eficazmente por la estructura de una página web.

5. **Estructura:** Una página web típica tiene una estructura jerárquica con elementos como `<html>`, `<head>` (que contiene metadatos), `<body>` (que contiene el contenido visible), y muchos otros elementos como encabezados, listas, imágenes, etc.

6. **Clases e IDs:** Los elementos HTML pueden tener clases y IDs, que son atributos utilizados para aplicar estilos y facilitar la identificación de elementos específicos en una página. Estos son útiles al realizar web scraping para seleccionar elementos específicos.

Para realizar web scraping, necesitas comprender cómo se organiza y etiqueta la información en una página web para poder identificar y extraer los datos que necesitas. El conocimiento de HTML es una base fundamental para esta tarea, ya que te permite navegar y seleccionar elementos específicos en el código fuente de una página web.

### BeautifulSoup

Beautiful Soup es una popular biblioteca de Python utilizada para analizar y extraer información de documentos HTML y XML de una manera sencilla y eficaz. Esta biblioteca proporciona herramientas para navegar y buscar elementos dentro de la estructura de un documento web, lo que la convierte en una herramienta esencial para tareas de web scraping y procesamiento de datos web. Beautiful Soup facilita la extracción de datos de una página web al proporcionar una interfaz amigable que permite acceder a etiquetas, atributos y contenido de manera intuitiva, lo que la convierte en una elección común entre los científicos de datos y desarrolladores que trabajan con datos web.

In [3]:
# !pip install beautifulsoup4

In [9]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
# from splinter import Browser
import numpy as np

pd.set_option('max_colwidth', 800)

In [13]:

from fake_useragent import UserAgent
url = "https://es.wikipedia.org/wiki/Fernando_Alonso"
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

In [14]:
print(response)

<Response [200]>

Ahora, estamos listos para solicitar nuestra primera página web. No es nada complicado: guardamos la URL que queremos raspar en la variable URL, luego solicitamos la URL (requests.get (url)) y guardamos la respuesta en la variable de respuesta:

In [ ]:
#url = "https://es.wikipedia.org/wiki/Fernando_Alonso"
#response = requests.get(url)

In [15]:
print(response)

<Response [200]>

Pero necesitamos el contenido HTML de la página web solicitada, así que como siguiente paso guardamos el contenido de la respuesta a html:

In [16]:
html = response.content

In [17]:
print(html)

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="es" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>Fernando Alonso - Wikipedia, la enciclopedia libre</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )eswikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\\t.","\xc2\xa0\\t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],"wgRequestId":"45458f49-852d-4897-81a7-ae11ed46e9a3","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Fernando_Alonso","wgTitle":"Fernando Alonso","wgCurRevisionId":170270835,"wgRevisionId":170270835,"wgArticleId":48666,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Wikipedia:P\xc3\xa1ginas con referencias con par\xc3\xa1metros obsoletos","Wikipedia:Art\xc3\xadculos destacados en la Wikipedia en indonesio","Wikipedia:Art\xc3\xadculos destacados en la Wikipedia en afrik\xc3\xa1ans","Wikipedia:Art\xc3\xadculos destacados en la Wikipedia en italiano","Wikipedia:Art\xc3\xadculos demasiado largos","Wikipedia:Art\xc3\xadculos con identificadores VIAF","Wikipedia:Art\xc3\xadculos con identificadores ISNI","Wikipedia:Art\xc3\xadculos con identificadores BNE","Wikipedia:Art\xc3\xadculos con identificadores BNF","Wikipedia:Art\xc3\xadculos con identificadores BNC","Wikipedia:Art\xc3\xadculos con identificadores CANTIC","Wikipedia:Art\xc3\xadculos con identificadores GND","Wikipedia:Art\xc3\xadculos con identificadores LCCN","Wikipedia:Art\xc3\xadculos con identificadores DeutscheBiographie","Wikipedia:Control de autoridades con 15 elementos","Personas vivas","Hombres","Nacidos en 1981","Fernando Alonso","Personas que dan nombre a un asteroide","Galardonados con los Premios Nacionales del Deporte"],"wgPageViewLanguage":"es","wgPageContentLanguage":"es","wgPageContentModel":"wikitext","wgRelevantPageName":"Fernando_Alonso","wgRelevantArticleId":48666,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgConfirmEditCaptchaNeededForGenericEdit":false,"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"es","pageLanguageDir":"ltr","pageVariantFallbacks":"es"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":true,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":300000,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[]},"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q10514","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":true,"wgGELevelingUpEnabledForUser":false};\nRLSTATE={"ext.gadget.imagenesinfobox":"ready","ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.xLab","ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.a-commons-directo","ext.gadget.ReferenceTooltips","ext.gadget.refToolbar","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=es&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">\n<script async="" src="/w/load.php?lang=es&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=es&amp;modules=ext.gadget.imagenesinfobox&amp;only=styles&amp;skin=vector-2022">\n<link rel="stylesheet" href="/w/load.php?lang=es&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">\n<noscript><link rel="stylesheet" href="/w/load.php?lang=es&amp;modules=noscript&amp;only=styles&amp;skin=vector-2022"></noscript>\n<meta name="generator" content="MediaWiki 1.45.0-wmf.25">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/2/2b/Alonso_2016.jpg">\n<meta property="og:image:width" content="959">\n<meta property="og:image:height" content="1200">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="Fernando Alonso - Wikipedia, la enciclopedia libre">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//upload.wikimedia.org">\n<link rel="alternate" type="application/x-wiki" title="Editar" href="/w/index.php?title=Fernando_Alonso&amp;action=edit">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (es)">\n<link rel="EditURI" type="application/rsd+xml" href="//es.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://es.wikipedia.org/wiki/Fernando_Alonso">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.es">\n<link rel="alternate" type="application/atom+xml" title="Canal Atom de Wikipedia" href="/w/index.php?title=Especial:CambiosRecientes&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="auth.wikimedia.org">\n</head>\n<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Fernando_Alonso rootpage-Fernando_Alonso skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Ir al contenido</a>\n<div class="vector-header-container">\n\t<header class="vector-header mw-header no-font-mode-scale">\n\t\t<div class="vector-header-start">\n\t\t\t<nav class="vector-main-menu-landmark" aria-label="Sitio">\n\t\t\t\t\n<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Men\xc3\xba principal" >\n\t<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Men\xc3\xba principal"  >\n\t<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>\n\n<span class="vector-dropdown-label-text">Men\xc3\xba principal</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t\t<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">\n\t\t\n<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">\n\t<div\n\tclass="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"\n\tdata-feature-name="main-menu-pinned"\n\tdata-pinnable-element-id="vector-main-menu"\n\tdata-pinned-container-id="vector-main-menu-pinned-container"\n\tdata-unpinned-container-id="vector-main-menu-unpinned-container"\n>\n\t<div class="vector-pinnable-header-label">Men\xc3\xba principal</div>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">mover a la barra lateral</button>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">ocultar</button>\n</div>\n\n\t\n<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >\n\t<div class="vector-menu-heading">\n\t\tNavegaci\xc3\xb3n\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Wikipedia:Portada" title="Visitar la p\xc3\xa1gina principal [z]" accesskey="z"><span>Portada</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Portal:Comunidad" title="Acerca del proyecto, lo que puedes hacer, d\xc3\xb3nde encontrar informaci\xc3\xb3n"><span>Portal de la comunidad</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Actualidad" title="Encuentra informaci\xc3\xb3n de contexto sobre acontecimientos actuales"><span>Actualidad</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Especial:CambiosRecientes" title="Lista de cambios recientes en la wiki [r]" accesskey="r"><span>Cambios recientes</span></a></li><li id="n-newpages" class="mw-list-item"><a href="/wiki/Especial:P%C3%A1ginasNuevas"><span>P\xc3\xa1ginas nuevas</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Especial:Aleatoria" title="Cargar una p\xc3\xa1gina al azar [x]" accesskey="x"><span>P\xc3\xa1gina aleatoria</span></a></li><li id="n-help" class="mw-list-item"><a href="/wiki/Ayuda:Contenidos" title="El lugar para aprender"><span>Ayuda</span></a></li><li id="n-bug_in_article" class="mw-list-item"><a href="/wiki/Wikipedia:Informes_de_error"><span>Notificar un error</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Especial:P%C3%A1ginasEspeciales"><span>P\xc3\xa1ginas especiales</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n</div>\n\n\t\t\t\t</div>\n\n\t</div>\n</div>\n\n\t\t</nav>\n\t\t\t\n<a href="/wiki/Wikipedia:Portada" class="mw-logo">\n\t<img class="mw-logo-icon" src="/static/images/icons/wikipedia.png" alt="" aria-hidden="true" height="50" width="50">\n\t<span class="mw-logo-container skin-invert">\n\t\t<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;">\n\t\t<img class="mw-logo-tagline" alt="La enciclopedia libre" src="/static/images/mobile/copyright/wikipedia-tagline-es.svg" width="120" height="13" style="width: 7.5em; height: 0.8125em;">\n\t</span>\n</a>\n\n\t\t</div>\n\t\t<div class="vector-header-end">\n\t\t\t\n<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">\n\t<a href="/wiki/Especial:Buscar" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Buscar en este wiki [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>\n\n<span>Buscar</span>\n\t</a>\n\t<div class="vector-typeahead-search-container">\n\t\t<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n\t\t\t<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">\n\t\t\t\t<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">\n\t\t\t\t\t<div class="cdx-text-input cdx-text-input--has-start-icon">\n\t\t\t\t\t\t<input\n\t\t\t\t\t\t\tclass="cdx-text-input__input mw-searchInput" autocomplete="off"\n\t\t\t\t\t\t\t type="search" name="search" placeholder="Buscar en Wikipedia" aria-label="Buscar en Wikipedia" autocapitalize="sentences" spellcheck="false" title="Buscar en este wiki [f]" accesskey="f" id="searchInput"\n\t\t\t\t\t\t\t>\n\t\t\t\t\t\t<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>\n\t\t\t\t\t</div>\n\t\t\t\t\t<input type="hidden" name="title" value="Especial:Buscar">\n\t\t\t\t</div>\n\t\t\t\t<button class="cdx-button cdx-search-input__end-button">Buscar</button>\n\t\t\t</form>\n\t\t</div>\n\t</div>\n</div>\n\n\t\t\t<nav class="vector-user-links vector-user-links-wide" aria-label="Herramientas personales">\n\t<div class="vector-user-links-main">\n\t\n<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t<nav class="vector-appearance-landmark" aria-label="Apariencia">\n\t\t\n<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Cambiar la apariencia del tama\xc3\xb1o, ancho y color de la fuente de la p\xc3\xa1gina" >\n\t<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Apariencia"  >\n\t<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>\n\n<span class="vector-dropdown-label-text">Apariencia</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">\n\t\t\t\t\n\t\t\t</div>\n\t\t\n\t</div>\n</div>\n\n\t</nav>\n\t\n<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=es.wikipedia.org&amp;uselang=es" class=""><span>Donaciones</span></a>\n</li>\n<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Especial:Crear_una_cuenta&amp;returnto=Fernando+Alonso" title="Te recomendamos crear una cuenta e iniciar sesi\xc3\xb3n; sin embargo, no es obligatorio" class=""><span>Crear una cuenta</span></a>\n</li>\n<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Especial:Entrar&amp;returnto=Fernando+Alonso" title="Te recomendamos iniciar sesi\xc3\xb3n, aunque no es obligatorio [o]" accesskey="o" class=""><span>Acceder</span></a>\n</li>\n\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t</div>\n\t\n<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out"  title="M\xc3\xa1s opciones" >\n\t<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Herramientas personales"  >\n\t<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>\n\n<span class="vector-dropdown-label-text">Herramientas personales</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\n<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="Men\xc3\xba de usuario" >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="pt-sitesupport" class="user-links-collapsible-item mw-list-item"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=es.wikipedia.org&amp;uselang=es"><span>Donaciones</span></a></li><li id="pt-createaccount" class="user-links-collapsible-item mw-list-item"><a href="/w/index.php?title=Especial:Crear_una_cuenta&amp;returnto=Fernando+Alonso" title="Te recomendamos crear una cuenta e iniciar sesi\xc3\xb3n; sin embargo, no es obligatorio"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Crear una cuenta</span></a></li><li id="pt-login" class="user-links-collapsible-item 

In [18]:
soup = bs(html, 'html.parser')

In [19]:
print(soup)

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="es">
<head>
<meta charset="utf-8"/>
<title>Fernando Alonso - Wikipedia, la enciclopedia libre</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )eswikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\t."," \t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],"wgRequestId":"45458f49-852d-4897-81a7-ae11ed46e9a3","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Fernando_Alonso","wgTitle":"Fernando Alonso","wgCurRevisionId":170270835,"wgRevisionId":170270835,"wgArticleId":48666,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Wikipedia:Páginas con referencias con parámetros obsoletos","Wikipedia:Artículos destacados en la Wikipedia en indonesio","Wikipedia:Artículos destacados en la Wikipedia en afrikáans","Wikipedia:Artículos destacados en la Wikipedia en italiano","Wikipedia:Artículos demasiado largos","Wikipedia:Artículos con identificadores VIAF","Wikipedia:Artículos con identificadores ISNI","Wikipedia:Artículos con identificadores BNE","Wikipedia:Artículos con identificadores BNF","Wikipedia:Artículos con identificadores BNC","Wikipedia:Artículos con identificadores CANTIC","Wikipedia:Artículos con identificadores GND","Wikipedia:Artículos con identificadores LCCN","Wikipedia:Artículos con identificadores DeutscheBiographie","Wikipedia:Control de autoridades con 15 elementos","Personas vivas","Hombres","Nacidos en 1981","Fernando Alonso","Personas que dan nombre a un asteroide","Galardonados con los Premios Nacionales del Deporte"],"wgPageViewLanguage":"es","wgPageContentLanguage":"es","wgPageContentModel":"wikitext","wgRelevantPageName":"Fernando_Alonso","wgRelevantArticleId":48666,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgConfirmEditCaptchaNeededForGenericEdit":false,"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"es","pageLanguageDir":"ltr","pageVariantFallbacks":"es"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":true,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":300000,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[]},"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q10514","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":true,"wgGELevelingUpEnabledForUser":false};
RLSTATE={"ext.gadget.imagenesinfobox":"ready","ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.xLab","ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.a-commons-directo","ext.gadget.ReferenceTooltips","ext.gadget.refToolbar","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=es&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=es&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=es&amp;modules=ext.gadget.imagenesinfobox&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<link href="/w/load.php?lang=es&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<noscript><link href="/w/load.php?lang=es&amp;modules=noscript&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/></noscript>
<meta content="MediaWiki 1.45.0-wmf.25" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/2/2b/Alonso_2016.jpg" property="og:image"/>
<meta content="959" property="og:image:width"/>
<meta content="1200" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="Fernando Alonso - Wikipedia, la enciclopedia libre" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=Fernando_Alonso&amp;action=edit" rel="alternate" title="Editar" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (es)" type="application/opensearchdescription+xml"/>
<link href="//es.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://es.wikipedia.org/wiki/Fernando_Alonso" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.es" rel="license"/>
<link href="/w/index.php?title=Especial:CambiosRecientes&amp;feed=atom" rel="alternate" title="Canal Atom de Wikipedia" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Fernando_Alonso rootpage-Fernando_Alonso skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Ir al contenido</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Sitio" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Menú principal">
<input aria-haspopup="true" aria-label="Menú principal" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Menú principal</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Menú principal</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">mover a la barra lateral</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">ocultar</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navegación
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Wikipedia:Portada" title="Visitar la página principal [z]"><span>Portada</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Portal:Comunidad" title="Acerca del proyecto, lo que puedes hacer, dónde encontrar información"><span>Portal de la comunidad</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Actualidad" title="Encuentra información de contexto sobre acontecimientos actuales"><span>Actualidad</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Especial:CambiosRecientes" title="Lista de cambios recientes en la wiki [r]"><span>Cambios recientes</span></a></li><li class="mw-list-item" id="n-newpages"><a href="/wiki/Especial:P%C3%A1ginasNuevas"><span>Páginas nuevas</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Especial:Aleatoria" title="Cargar una página al azar [x]"><span>Página aleatoria</span></a></li><li class="mw-list-item" id="n-help"><a href="/wiki/Ayuda:Contenidos" title="El lugar para aprender"><span>Ayuda</span></a></li><li class="mw-list-item" id="n-bug_in_article"><a href="/wiki/Wikipedia:Informes_de_error"><span>Notificar un error</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Especial:P%C3%A1ginasEspeciales"><span>Páginas especiales</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Wikipedia:Portada">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="La enciclopedia libre" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-es.svg" style="width: 7.5em; height: 0.8125em;" width="120"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Especial:Buscar" title="Buscar en este wiki [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Buscar</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Buscar en Wikipedia" autocapitalize="sentences" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Buscar en Wikipedia" spellcheck="false" title="Buscar en este wiki [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Especial:Buscar"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Buscar</button>
</form>
</div>
</div>
</div>
<nav aria-label="Herramientas personales" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Apariencia" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Cambiar la apariencia del tamaño, ancho y color de la fuente de la página">
<input aria-haspopup="true" aria-label="Apariencia" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Apariencia</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=es.wikipedia.org&amp;uselang=es"><span>Donaciones</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Especial:Crear_una_cuenta&amp;returnto=Fernando+Alonso" title="Te recomendamos crear una cuenta e iniciar sesión; sin embargo, no es obligatorio"><span>Crear una cuenta</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Especial:Entrar&amp;returnto=Fernando+Alonso" title="Te recomendamos iniciar sesión, aunque no es obligatorio [o]"><span>Acceder</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Más opciones">
<input aria-haspopup="true" aria-label="Herramientas personales" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Herramientas personales</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="Menú de usuario">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=es.wikipedia.org&amp;uselang=es"><span>Donaciones</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Especial:Crear_una_cuenta&amp;returnto=Fernando+Alonso" title="Te recomendamos crear una cuenta e iniciar sesión; sin embargo, no es obligatorio"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Crear una cuenta</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Especial:Entrar&amp;returnto=Fernando+Alonso" title="Te recomendamos iniciar sesión, aunque no es obligatorio [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Acceder</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Páginas para editores desconectados <a aria-label="Obtenga más información sobre editar" href="/wiki/Ayuda:Introducci%C3%B3n"><span>más información</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="pt-anoncontribs"><a accesskey="y" href="/wiki/Especial:MisContribuciones" title="Una lista de modificaciones hechas desde esta dirección IP [y]"><span>Contribuciones</span></a></li><li class="mw-list-item" id="pt-anontalk"><a accesskey="n" href="/wiki/Especial:MiDiscusi%C3%B3n" title="Discusión sobre ediciones hechas desde esta dirección IP [n]"><span>Discusión</span></a></li>

Ahora que hemos aprendido algo de HTML básico, finalmente podemos comenzar a extraer datos de soup. Simplemente escriba un nombre de etiqueta después de soup y un punto (como soup.title), y observe cómo se desarrolla la magia:

In [20]:
soup.title

In [21]:
soup.h1

In [22]:
soup.h1.get_text()

'Fernando Alonso'

¿Qué sucede si solo necesita el atributo de un elemento?

In [23]:
soup.a

In [24]:
soup.a['href']

'#bodyContent'

In [25]:
print("Sin utilizar método .find()")
print(soup.a)
print("")
print("Utilizando método .find()")
print(soup.find("a"))

Sin utilizar método .find()
<a class="mw-jump-link" href="#bodyContent">Ir al contenido</a>

Utilizando método .find()
<a class="mw-jump-link" href="#bodyContent">Ir al contenido</a>

In [31]:
soup.find("tbody").find("img")["src"]

'//upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Alonso_2016.jpg/250px-Alonso_2016.jpg'

In [33]:
soup.find_all('div')

[<div class="vector-header-container">
 <header class="vector-header mw-header no-font-mode-scale">
 <div class="vector-header-start">
 <nav aria-label="Sitio" class="vector-main-menu-landmark">
 <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Menú principal">
 <input aria-haspopup="true" aria-label="Menú principal" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
 <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
 <span class="vector-dropdown-label-text">Menú principal</span>
 </label>
 <div class="vector-dropdown-content">
 <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
 <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
 <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
 <div class="vector-pinnable-header-label">Menú principal</div>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">mover a la barra lateral</button>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">ocultar</button>
 </div>
 <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
 <div class="vector-menu-heading">
 		Navegación
 	</div>
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 <li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Wikipedia:Portada" title="Visitar la página principal [z]"><span>Portada</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Portal:Comunidad" title="Acerca del proyecto, lo que puedes hacer, dónde encontrar información"><span>Portal de la comunidad</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Actualidad" title="Encuentra información de contexto sobre acontecimientos actuales"><span>Actualidad</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Especial:CambiosRecientes" title="Lista de cambios recientes en la wiki [r]"><span>Cambios recientes</span></a></li><li class="mw-list-item" id="n-newpages"><a href="/wiki/Especial:P%C3%A1ginasNuevas"><span>Páginas nuevas</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Especial:Aleatoria" title="Cargar una página al azar [x]"><span>Página aleatoria</span></a></li><li class="mw-list-item" id="n-help"><a href="/wiki/Ayuda:Contenidos" title="El lugar para aprender"><span>Ayuda</span></a></li><li class="mw-list-item" id="n-bug_in_article"><a href="/wiki/Wikipedia:Informes_de_error"><span>Notificar un error</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Especial:P%C3%A1ginasEspeciales"><span>Páginas especiales</span></a></li>
 </ul>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>
 </nav>
 <a class="mw-logo" href="/wiki/Wikipedia:Portada">
 <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
 <span class="mw-logo-container skin-invert">
 <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
 <img alt="La enciclopedia libre" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-es.svg" style="width: 7.5em; height: 0.8125em;" width="120"/>
 </span>
 </a>
 </div>
 <div class="vector-header-end">
 <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
 <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Especial:Buscar" title="Buscar en este wiki [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
 <span>Buscar</span>
 </a>
 <div class="vector-typeahead-search-container">
 <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
 <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
 <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
 <div class="cdx-text-input cdx-text-input--has-start-icon">
 <input accesskey="f" aria-label="Buscar en Wikipedia" autocapitalize="sentences" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Buscar en Wikipedia" spellcheck="false" title="Buscar en este wiki [f]" type="search"/>
 <span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
 </div>
 <input name="title" type="hidden" value="Especial:Buscar"/>
 </div>
 <button class="cdx-button cdx-search-input__end-button">Buscar</button>
 </form>
 </div>
 </div>
 </div>
 <nav aria-label="Herramientas personales" class="vector-user-links vector-user-links-wide">
 <div class="vector-user-links-main">
 <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 </ul>
 </div>
 </div>
 <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 </ul>
 </div>
 </div>
 <nav aria-label="Apariencia" class="vector-appearance-landmark">
 <div class="vector-dropdown" id="vector-appearance-dropdown" title="Cambiar la apariencia del tamaño, ancho y color de la fuente de la página">
 <input aria-haspopup="true" aria-label="Apariencia" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
 <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
 <span class="vector-dropdown-label-text">Apariencia</span>
 </label>
 <div class="vector-dropdown-content">
 <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
 </div>
 </div>
 </div>
 </nav>
 <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 </ul>
 </div>
 </div>
 <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=es.wikipedia.org&amp;uselang=es"><span>Donaciones</span></a>
 </li>
 <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Especial:Crear_una_cuenta&amp;returnto=Fernando+Alonso" title="Te recomendamos crear una cuenta e iniciar sesión; sin embargo, no es obligatorio"><span>Crear una cuenta</span></a>
 </li>
 <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Especial:Entrar&amp;returnto=Fernando+Alonso" title="Te recomendamos iniciar sesión, aunque no es obligatorio [o]"><span>Acceder</span></a>
 </li>
 </ul>
 </div>
 </div>
 </div>
 <div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Más opciones">
 <input aria-haspopup="true" aria-label="Herramientas personales" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
 <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
 <span class="vector-dropdown-label-text">Herramientas personales</span>
 </label>
 <div class="vector-dropdown-content">
 <div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="Menú de usuario">
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 <li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=es.wikipedia.org&amp;uselang=es"><span>Donaciones</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Especial:Crear_una_cuenta&amp;returnto=Fernando+Alonso" title="Te recomendamos crear una cuenta e iniciar sesión; sin embargo, no es obligatorio"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Crear una cuenta</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Especial:Entrar&amp;returnto=Fernando+Alonso" title="Te recomendamos iniciar sesión, aunque no es obligatorio [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Acceder</span></a></li>
 </ul>
 </div>
 </div>
 <div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
 <div class="vector-menu-heading">
 		Páginas para editores desconectados <a aria-label="Obtenga más información sobre editar" href="/wiki/Ayuda:Introducci%C3%B3n"><span>más información</span></a>
 </div>
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 <li class="mw-list-item" id="pt-anoncontribs"><a accesskey="y" href="/wiki/Especial:MisContribuciones" title="Una lista de modificaciones hechas desde esta dirección IP [y]"><span>Contribuciones</span></a></li><li class="mw-list-item" id="pt-anontalk"><a accesskey="n" href="/wiki/Especial:MiDiscusi%C3%B3n" title="Discusión sobre ediciones hechas desde esta dirección IP [n]"><span>Discusión</span></a></li>
 </ul>
 </div>
 </div>
 </div>
 </div>
 </nav>
 </div>
 </header>
 </div>,
 <div class="vector-header-start">
 <nav aria-label="Sitio" class="vector-main-menu-landmark">
 <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Menú principal">
 <input aria-haspopup="true" aria-label="Menú principal" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
 <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
 <span class="vector-dropdown-label-text">Menú principal</span>
 </label>
 <div class="vector-dropdown-content">
 <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
 <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
 <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
 <div class="vector-pinnable-header-label">Menú principal</div>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">mover a la barra lateral</button>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">ocultar</button>
 </div>
 <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
 <div class="vector-menu-heading">
 		Navegación
 	</div>
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 <li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Wikipedia:Portada" title="Visitar la página principal [z]"><span>Portada</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Portal:Comunidad" title="Acerca del proyecto, lo que puedes hacer, dónde encontrar información"><span>Portal de la comunidad</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Actualidad" title="Encuentra información de contexto sobre acontecimientos actuales"><span>Actualidad</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Especial:CambiosRecientes" title="Lista de cambios recientes en la wiki [r]"><span>Cambios recientes</span></a></li><li class="mw-list-item" id="n-newpages"><a href="/wiki/Especial:P%C3%A1ginasNuevas"><span>Páginas nuevas</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Especial:Aleatoria" title="Cargar una página al azar [x]"><span>Página aleatoria</span></a></li><li class="mw-list-item" id="n-help"><a href="/wiki/Ayuda:Contenidos" title="El lugar para aprender"><span>Ayuda</span></a></li><li class="mw-list-item" id="n-bug_in_article"><a href="/wiki/Wikipedia:Informes_de_error"><span>Notificar un error</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Especial:P%C3%A1ginasEspeciales"><span>Páginas especiales</span></a></li>
 </ul>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>
 </nav>
 <a class="mw-logo" href="/wiki/Wikipedia:Portada">
 <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
 <span class="mw-logo-container skin-invert">
 <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
 <img alt="La enciclopedia libre" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-es.svg" style="width: 7.5em; height: 0.8125em;" width="120"/>
 </span>
 </a>
 </div>,
 <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Menú principal">
 <input aria-haspopup="true" aria-label="Menú principal" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
 <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
 <span class="vector-dropdown-label-text">Menú principal</span>
 </label>
 <div class="vector-dropdown-content">
 <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
 <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
 <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
 <div class="vector-pinnable-header-label">Menú principal</div>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">mover a la barra lateral</button>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">ocultar</button>
 </div>
 <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
 <div class="vector-menu-heading">
 		Navegación
 	</div>
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">
 <li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Wikipedia:Portada" title="Visitar la página principal [z]"><span>Portada</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Portal:Comunidad" title="Acerca del proyecto, lo que puedes hacer, dónde encontrar información"><span>Portal de la comunidad</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Actualidad" title="Encuentra información de contexto sobre acontecimientos actuales"><span>Actualidad</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Especial:CambiosRecientes" title="Lista de cambios recientes en la wiki [r]"><span>Cambios recientes</span></a></li><li class="mw-list-item" id="n-newpages"><a href="/wiki/Especial:P%C3%A1ginasNuevas"><span>Páginas nuevas</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Especial:Aleatoria" title="Cargar una página al azar [x]"><span>Página aleatoria</span></a></li><li class="mw-list-item" id="n-help"><a href="/wiki/Ayuda:Contenidos" title="El lugar para aprender"><span>Ayuda</span></a></li><li class="mw-list-item" id="n-bug_in_article"><a href="/wiki/Wikipedia:Informes_de_error"><span>Notificar un error</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Especial:P%C3%A1ginasEspeciales"><span>Páginas especiales</span></a></li>
 </ul>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="vector-dropdown-content">
 <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
 <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
 <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
 <div class="vector-pinnable-header-label">Menú principal</div>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">mover a la barra lateral</button>
 <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">ocultar</button>
 </div>
 <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
 <div class="vector-menu-heading">
 		Navegación
 	</div>
 <div class="vector-menu-content">
 <ul class="vector-menu-content-list">

In [34]:
all_a = soup.find_all('a')
for a in all_a[:5]:
    print(a)

<a class="mw-jump-link" href="#bodyContent">Ir al contenido</a>
<a accesskey="z" href="/wiki/Wikipedia:Portada" title="Visitar la página principal [z]"><span>Portada</span></a>
<a href="/wiki/Portal:Comunidad" title="Acerca del proyecto, lo que puedes hacer, dónde encontrar información"><span>Portal de la comunidad</span></a>
<a href="/wiki/Portal:Actualidad" title="Encuentra información de contexto sobre acontecimientos actuales"><span>Actualidad</span></a>
<a accesskey="r" href="/wiki/Especial:CambiosRecientes" title="Lista de cambios recientes en la wiki [r]"><span>Cambios recientes</span></a>

In [35]:
all_a = soup.find_all('a')
for a in all_a[:5]:
    print(a.get_text())

Ir al contenido
Portada
Portal de la comunidad
Actualidad
Cambios recientes

In [24]:
all_a = soup.find_all('a')
for a in all_a[:5]:
    print(a['href'])

https://www.filmaffinity.com/es/main.html
https://www.filmaffinity.com/es/advsearch.php
https://www.filmaffinity.com/es/login.php
https://www.filmaffinity.com/es/register.php
https://www.filmaffinity.com/es/topgen.php

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Obtener textos menú cabecera</h3>
Top FA| Rankings FA| Año 2023| Calendario Series| Últ. críticas| Tráilers| Premios
      
<ol>
    <li>Obtén los textos con find_all y un bucle</li>
    <li>Obtén los links con find_all y un bucle</li>
    <li>Almacena la información en un dataframe</li>
</ol>
         
 </td></tr>
</table>

In [ ]:
/html/body/header/div[2]/div/ul/li[1]/a

In [35]:
soup.find_all("a")[4:12]

[<a href="https://www.filmaffinity.com/es/topgen.php">Top FA</a>,
 <a href="https://www.filmaffinity.com/es/rankings.php">Rankings FA</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=2024films">Cine 2024</a>,
 <a href="https://www.filmaffinity.com/es/best_2023.php">Resumen 2023</a>,
 <a href="https://www.filmaffinity.com/es/calendar-tv.php">Calendario Series</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=latest_reviews">Últ. críticas</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=TRAILERS">Tráilers</a>,
 <a href="https://www.filmaffinity.com/es/all_awards.php">Premios</a>]

In [37]:
for x in soup.find_all("a")[4:12]:
    print(x.get_text())
    print(x['href'])

Top FA
https://www.filmaffinity.com/es/topgen.php
Rankings FA
https://www.filmaffinity.com/es/rankings.php
Cine 2024
https://www.filmaffinity.com/es/category.php?id=2024films
Resumen 2023
https://www.filmaffinity.com/es/best_2023.php
Calendario Series
https://www.filmaffinity.com/es/calendar-tv.php
Últ. críticas
https://www.filmaffinity.com/es/category.php?id=latest_reviews
Tráilers
https://www.filmaffinity.com/es/category.php?id=TRAILERS
Premios
https://www.filmaffinity.com/es/all_awards.php

In [42]:
for x in soup.find_all("ul")[0].find_all('a'):
    print(x.get_text())
    print(x['href'])

Top FA
https://www.filmaffinity.com/es/topgen.php
Rankings FA
https://www.filmaffinity.com/es/rankings.php
Cine 2024
https://www.filmaffinity.com/es/category.php?id=2024films
Resumen 2023
https://www.filmaffinity.com/es/best_2023.php
Calendario Series
https://www.filmaffinity.com/es/calendar-tv.php
Últ. críticas
https://www.filmaffinity.com/es/category.php?id=latest_reviews
Tráilers
https://www.filmaffinity.com/es/category.php?id=TRAILERS
Premios
https://www.filmaffinity.com/es/all_awards.php

In [49]:
menu_dict = {"Texto": [],
             "Enlace": []}

for x in soup.find_all("a")[4:12]:
    menu_dict['Texto'].append(x.get_text())
    menu_dict['Enlace'].append(x['href'])

df = pd.DataFrame(menu_dict)
df.to_csv("enlaces_menus.csv")
df

,Texto,Enlace
0,Top FA,https://www.filmaffinity.com/es/topgen.php
1,Rankings FA,https://www.filmaffinity.com/es/rankings.php
2,Cine 2024,https://www.filmaffinity.com/es/category.php?id=2024films
3,Resumen 2023,https://www.filmaffinity.com/es/best_2023.php
4,Calendario Series,https://www.filmaffinity.com/es/calendar-tv.php
5,Últ. críticas,https://www.filmaffinity.com/es/category.php?id=latest_reviews
6,Tráilers,https://www.filmaffinity.com/es/category.php?id=TRAILERS
7,Premios,https://www.filmaffinity.com/es/all_awards.php

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Obtener películas y nota</h3>
      
<ol>
    <li>Obtén los títulos de las top 10 películas</li>
    <li>Obtén el rating de las top 10 películas</li>
    <li>Almacena la información en un dataframe</li>
</ol>
         
 </td></tr>
</table>

In [ ]:
/html/body/div[3]/div/div/main/div[2]/ul/li[1]/ul/li[2]/div/div[2]/div[1]/a

In [58]:
soup.find('div', class_="mc-title").get_text()

'El padrino'

In [61]:
len(soup.find_all('div', class_="mc-title"))

30

In [63]:
for x in soup.find_all('div', class_="mc-title")[:10]:
    print(x.get_text())

El padrino
Planeta Tierra II
El padrino. Parte II
The Wire (Bajo escucha)
Breaking Bad
Cosmos
Planeta azul II
12 hombres sin piedad
Cosmos: A Space-Time Odyssey
La lista de Schindler

In [64]:
for x in soup.find_all('div', class_="avg-rating")[:10]:
    print(x.get_text())

9,0
8,9
8,9
8,8
8,8
8,8
8,8
8,7
8,6
8,6

In [66]:
top10_dict = {"Titulo": [x.get_text() for x in soup.find_all('div', class_="mc-title")[:10]],
             "Nota": [x.get_text() for x in soup.find_all('div', class_="avg-rating")[:10]]}
df = pd.DataFrame(top10_dict)
df.to_csv("top10.csv")
df

                         Titulo Nota
0                    El padrino  9,0
1             Planeta Tierra II  8,9
2          El padrino. Parte II  8,9
3       The Wire (Bajo escucha)  8,8
4                  Breaking Bad  8,8
5                        Cosmos  8,8
6               Planeta azul II  8,8
7         12 hombres sin piedad  8,7
8  Cosmos: A Space-Time Odyssey  8,6
9         La lista de Schindler  8,6

In [67]:
df.dtypes

Titulo    object
Nota      object
dtype: object